import 'dart:io';
import 'package:shared_preferences/shared_preferences.dart';
import 'package:flutter_thermal_printer/flutter_thermal_printer.dart';
import 'package:flutter_thermal_printer/utils/printer.dart';

/// A centralized service to manage hardware printer connection and execution.
/// This service is now "dumb": it does not care about receipt layouts.
/// It only cares about taking an array of bytes and sending it to a printer.
class PrinterService {
  static const String _printerKey = 'saved_printer_name';

  /// Fetches the currently saved printer name from local storage.
  static Future<String> getPrinterName() async {
    final prefs = await SharedPreferences.getInstance();
    return prefs.getString(_printerKey) ?? '';
  }

  /// Saves the printer [name] to local storage for future print jobs.
  static Future<void> setPrinterName(String name) async {
    final prefs = await SharedPreferences.getInstance();
    await prefs.setString(_printerKey, name);
  }

  /// Main entry point for hardware printing.
  /// Takes a raw byte array generated by a Layout class (e.g., OrderReceiptLayout)
  /// and sends it to the target printer.
  static Future<String?> printBytes(List<int> bytes, String printerName) async {
    try {
      final isPrinterFound = await _sendToPrinter(bytes, printerName);

      if (!isPrinterFound) {
        return 'Could not find printer "$printerName". Please check connections.';
      }

      return null; // Success! No error message.
    } catch (e) {
      return 'Hardware Printing error: ${e.toString()}';
    }
  }

  static Future<bool> _sendToPrinter(
    List<int> bytes,
    String printerName,
  ) async {
    print("DEBUG: _sendToPrinter started for $printerName");

    final flutterThermalPrinterPlugin = FlutterThermalPrinter.instance;

    Printer? targetPrinter;
    bool isDiscovering = true;

    // Listen to the stream and instantly flag when we find the right printer
    final subscription = flutterThermalPrinterPlugin.devicesStream.listen((
      printers,
    ) {
      for (var printer in printers) {
        if (printer.name?.trim().toLowerCase() ==
            printerName.trim().toLowerCase()) {
          targetPrinter = printer;
        }
      }
    });

    print("DEBUG: Calling getPrinters...");
    // Scan for USB devices
    await flutterThermalPrinterPlugin.getPrinters(
      connectionTypes: [ConnectionType.USB],
    );
    print("DEBUG: getPrinters called. Waiting for stream discovery...");

    // Actively wait for up to 4 seconds for the specific printer to appear in the stream
    for (int i = 0; i < 20; i++) {
      if (targetPrinter != null) break;
      await Future.delayed(const Duration(milliseconds: 200));
    }

    await subscription.cancel();

    print("DEBUG: Target printer found? ${targetPrinter != null}");
    if (targetPrinter == null) {
      return false; // Printer not found
    }

    // Connect to the printer if not already connected
    print("DEBUG: Target printer isConnected: ${targetPrinter!.isConnected}");
    if (!(targetPrinter!.isConnected ?? false)) {
      print("DEBUG: Calling connect...");
      await flutterThermalPrinterPlugin.connect(targetPrinter!);
      print("DEBUG: Connect returned.");
    }

    print("DEBUG: Calling printData...");
    // Send the raw ESC/POS payload directly to the hardware buffer
    await flutterThermalPrinterPlugin.printData(targetPrinter!, bytes);
    print("DEBUG: printData returned.");

    // Disconnect to free up the hardware
    await flutterThermalPrinterPlugin.disconnect(targetPrinter!);
    print("DEBUG: Printer disconnected.");

    return true;
  }
}
