import 'dart:io';
import 'dart:convert';
import 'package:shared_preferences/shared_preferences.dart';
import 'package:flutter_thermal_printer/flutter_thermal_printer.dart';
import 'package:flutter_thermal_printer/utils/printer.dart';
import 'package:esc_pos_utils_plus/esc_pos_utils_plus.dart';

/// A centralized service to manage hardware printer connection and execution.
/// It only cares about taking an array of bytes and sending it to a printer.
class PrinterService {
  static Future<SharedPreferences> get _prefs => SharedPreferences.getInstance();

  static const String _printerKey = 'saved_printer_name';

  // Android Generic Printer Key (Supports both USB and BLE)
  static const String _androidPrinterKey = 'saved_android_printer';

  /// Fetches the currently saved Android printer object (BLE or USB).
  static Future<Printer?> getAndroidPrinter() async {
    final prefs = await _prefs;
    final String? printerJson = prefs.getString(_androidPrinterKey);
    if (printerJson != null && printerJson.isNotEmpty) {
      try {
        return Printer.fromJson(jsonDecode(printerJson));
      } catch (e) {
        print("DEBUG: Failed to parse saved Android printer - $e");
      }
    }
    return null;
  }

  /// Saves the selected Android printer (BLE or USB) for future print jobs.
  static Future<void> setAndroidPrinter(Printer printer) async {
    final prefs = await _prefs;
    await prefs.setString(_androidPrinterKey, jsonEncode(printer.toJson()));
  }

  /// Fetches the currently saved printer name from local storage.
  static Future<String> getPrinterName() async {
    final prefs = await _prefs;
    return prefs.getString(_printerKey) ?? '';
  }

  /// Saves the printer [name] to local storage for future print jobs.
  static Future<void> setPrinterName(String name) async {
    final prefs = await _prefs;
    await prefs.setString(_printerKey, name);
  }

  /// Checks if a printer is currently configured for the active platform.
  static Future<bool> hasConfiguredPrinter() async {
    if (Platform.isAndroid) {
      final printer = await getAndroidPrinter();
      return printer != null;
    } else {
      final name = await getPrinterName();
      return name.isNotEmpty;
    }
  }

  /// Main entry point for hardware printing.
  /// Usage: String? error = await PrinterService.printBytes(bytes);
  /// 
  /// This takes a raw byte array generated by a Layout class (e.g., OrderReceiptLayout)
  /// and automatically routes it to either Bluetooth (Android) or USB (Windows) 
  /// based on the current operating system.
  static Future<String?> printBytes(List<int> bytes, {String printerName = ''}) async {
    try {
      if (Platform.isAndroid) {
        // --- Android: Route to BLE or USB Printing ---
        
        // 1. Fetch the generic printer object we saved earlier
        final Printer? savedPrinter = await getAndroidPrinter();
        
        if (savedPrinter == null) {
          return 'No Android printer configured! Please set it up on the Home Page.';
        }
        
        // 2. Attempt to print using the saved config
        final isPrinterFound = await _sendToAndroidPrinter(bytes, savedPrinter);
        
        if (!isPrinterFound) {
          return 'Could not find Android printer "${savedPrinter.name}". Is it turned on and connected?';
        }
        
        return null; // Success! No error message.
        
      } else {
        // --- Windows/Desktop: Route to USB Printing ---
        
        final isPrinterFound = await _sendToPrinter(bytes, printerName);

        if (!isPrinterFound) {
          return 'Could not find USB printer "$printerName". Please check connections.';
        }

        return null; // Success! No error message.
      }
    } catch (e) {
      return 'Hardware Printing error: ${e.toString()}';
    }
  }

  /// Generates a tiny receipt and prints it to the specified Android printer 
  /// without requiring it to be the default saved printer.
  /// Usage: Used strictly for testing connections before saving.
  static Future<String?> testAndroidPrint(Printer testPrinter) async {
    try {
      // 1. Load the generic ESC/POS capability profile
      final profile = await CapabilityProfile.load();
      // 2. Initialize generator for 80mm paper (works fine on 58mm for small text too)
      final generator = Generator(PaperSize.mm80, profile);
      
      List<int> bytes = [];
      
      // 3. Add text with center alignment and bold font
      bytes += generator.text(
        'Test Print Successful!', 
        styles: const PosStyles(align: PosAlign.center, bold: true, height: PosTextSize.size2, width: PosTextSize.size2),
      );
      
      // 4. Feed a few lines of paper and send a cut command
      bytes += generator.feed(2);
      bytes += generator.cut();

      // 5. Route directly to the internal method using the specified printer
      final isFound = await _sendToAndroidPrinter(bytes, testPrinter);
      
      if (!isFound) {
        return 'Printer not found. Is it turned on and connected?';
      }
      return null; // Success! No error
    } catch (e) {
      return 'Test Print Error: $e';
    }
  }

  /// Internal method to scan for and print to a specific Android printer (BLE or USB).
  /// Usage: Automatically called by [printBytes] when running on Android.
  static Future<bool> _sendToAndroidPrinter(
    List<int> bytes,
    Printer targetPrinter,
  ) async {
    print("DEBUG: _sendToAndroidPrinter scanning for: ${targetPrinter.name}");

    final plugin = FlutterThermalPrinter.instance;
    Printer? discoveredPrinter;

    // 1. Listen to the stream and instantly flag when we find a match
    final subscription = plugin.devicesStream.listen((printers) {
      for (var printer in printers) {
        // Match by address (BLE) or by vendorId (USB)
        if (printer.address != null && printer.address == targetPrinter.address) {
          discoveredPrinter = printer;
        } else if (printer.vendorId != null && printer.vendorId == targetPrinter.vendorId) {
          discoveredPrinter = printer;
        }
      }
    });

    print("DEBUG: Scanning for Android devices...");
    // 2. Tell the plugin to scan ONLY for the connection type of the target printer
    // This avoids crashing the BLE scanner on custom POS hardware if the target is a USB printer.
    final List<ConnectionType> scanType = targetPrinter.connectionType != null 
        ? [targetPrinter.connectionType!] 
        : [ConnectionType.USB];
        
    try {
      await plugin.getPrinters(connectionTypes: scanType);
    } catch (e) {
      print("DEBUG: Printer scan threw an exception (Likely OS permission denied) - $e");
    }
    
    // 3. Actively wait for up to 10 seconds for the printer to appear in the stream
    for (int i = 0; i < 50; i++) {
      if (discoveredPrinter != null) break;
      await Future.delayed(const Duration(milliseconds: 200));
    }

    // Stop listening to the stream once we are done scanning
    await subscription.cancel();

    print("DEBUG: Target Android printer found? ${discoveredPrinter != null}");
    if (discoveredPrinter == null) {
      return false; // The printer was not found nearby
    }

    // 4. Connect to the printer if not already connected
    print("DEBUG: Target Android printer isConnected: ${discoveredPrinter!.isConnected}");
    if (!(discoveredPrinter!.isConnected ?? false)) {
      print("DEBUG: Connecting to Android printer...");
      await plugin.connect(discoveredPrinter!);
    }

    print("DEBUG: Sending data buffer...");
    // 5. Send the raw ESC/POS bytes directly to the printer's hardware buffer
    await plugin.printData(discoveredPrinter!, bytes);
    
    // We intentionally DO NOT disconnect the printer here. 
    // Disconnecting forces the Android hardware stack to cold-restart the connection 
    // on the next print, which can take 5-10 seconds and often causes timeouts.
    print("DEBUG: Android Printer data sent (Connection kept alive).");

    return true;
  }

  static Future<bool> _sendToPrinter(
    List<int> bytes,
    String printerName,
  ) async {
    print("DEBUG: _sendToPrinter started for $printerName");

    final flutterThermalPrinterPlugin = FlutterThermalPrinter.instance;

    Printer? targetPrinter;
    bool isDiscovering = true;

    // Listen to the stream and instantly flag when we find the right printer
    final subscription = flutterThermalPrinterPlugin.devicesStream.listen((
      printers,
    ) {
      for (var printer in printers) {
        if (printer.name?.trim().toLowerCase() ==
            printerName.trim().toLowerCase()) {
          targetPrinter = printer;
        }
      }
    });

    print("DEBUG: Calling getPrinters...");
    // Scan for USB devices
    await flutterThermalPrinterPlugin.getPrinters(
      connectionTypes: [ConnectionType.USB],
    );
    print("DEBUG: getPrinters called. Waiting for stream discovery...");

    // Actively wait for up to 4 seconds for the specific printer to appear in the stream
    for (int i = 0; i < 20; i++) {
      if (targetPrinter != null) break;
      await Future.delayed(const Duration(milliseconds: 200));
    }

    await subscription.cancel();

    print("DEBUG: Target printer found? ${targetPrinter != null}");
    if (targetPrinter == null) {
      return false; // Printer not found
    }

    // Connect to the printer if not already connected
    print("DEBUG: Target printer isConnected: ${targetPrinter!.isConnected}");
    if (!(targetPrinter!.isConnected ?? false)) {
      print("DEBUG: Calling connect...");
      await flutterThermalPrinterPlugin.connect(targetPrinter!);
      print("DEBUG: Connect returned.");
    }

    print("DEBUG: Calling printData...");
    // Send the raw ESC/POS payload directly to the hardware buffer
    await flutterThermalPrinterPlugin.printData(targetPrinter!, bytes);
    print("DEBUG: printData returned.");

    // Disconnect to free up the hardware
    await flutterThermalPrinterPlugin.disconnect(targetPrinter!);
    print("DEBUG: Printer disconnected.");

    return true;
  }
}
