// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyB9oJk32aSjTVwYDZywFU2n_vH30GeDdYo',
    appId: '1:525386092336:web:cb60e9eb2bc1ab327bc2f5',
    messagingSenderId: '525386092336',
    projectId: 'web-6e61c',
    authDomain: 'web-6e61c.firebaseapp.com',
    storageBucket: 'web-6e61c.firebasestorage.app',
    measurementId: 'G-2830VG0FXY',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBuFmFeKHHj8YCoWRrynyly2racgyTSKvo',
    appId: '1:525386092336:android:73b70c0b92a659dc7bc2f5',
    messagingSenderId: '525386092336',
    projectId: 'web-6e61c',
    storageBucket: 'web-6e61c.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCVMpJNOfhrVEL9DOOVwZhpL_FSBzMMWXE',
    appId: '1:525386092336:ios:10fc0c58d6c6d13b7bc2f5',
    messagingSenderId: '525386092336',
    projectId: 'web-6e61c',
    storageBucket: 'web-6e61c.firebasestorage.app',
    iosBundleId: 'com.example.webProject',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCVMpJNOfhrVEL9DOOVwZhpL_FSBzMMWXE',
    appId: '1:525386092336:ios:10fc0c58d6c6d13b7bc2f5',
    messagingSenderId: '525386092336',
    projectId: 'web-6e61c',
    storageBucket: 'web-6e61c.firebasestorage.app',
    iosBundleId: 'com.example.webProject',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyB9oJk32aSjTVwYDZywFU2n_vH30GeDdYo',
    appId: '1:525386092336:web:a63d20d53b79f3167bc2f5',
    messagingSenderId: '525386092336',
    projectId: 'web-6e61c',
    authDomain: 'web-6e61c.firebaseapp.com',
    storageBucket: 'web-6e61c.firebasestorage.app',
    measurementId: 'G-L679KBB2VQ',
  );
}
